server:
  port: 8001
spring:
  application:
    name: user-consumer
eureka:
  client:
    service-url:
      #defaultZone: http://eureka1.com:6001/eureka,http://eureka2.com:6002/eureka
      defaultZone: http://localhost:6001/eureka

#服务降级的开关
feign:
  hystrix:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
        #include: hystrix.stream
  endpoint:
    health:
      show-details: ALWAYS

con:     
  info: coninfo test22222222
